PCA

---

First lets discuss the steps in PCA



1.   Get Data
2.   Normalize the data
3.   Subtract the mean
4.   Calculate the covariance matrix
5.   Calculate eigen values and eigen vectors
6.   Choose components and feature vector
7.   Derive the new dataset

Here I am using IPL 2018 dataset. 


<table><tbody><tr><td><strong>Slno </strong></td><td><strong> Name </strong></td><td> <strong>Runs (x) </strong></td><td><strong> Average(y) </strong></td></tr><tr><td>
1</td><td>Kane Williamson </td><td>735</td><td>52.5</td></tr><tr><td>
2</td><td>Rishabh Pant </td><td>684</td><td>52.61</td></tr><tr><td>
3</td><td>Lokesh Rahul </td><td>659</td><td>54.91</td></tr><tr><td>
4</td><td>Ambati Rayudu </td><td>602</td><td>43</td></tr><tr><td>
5</td><td>Shane Watson </td><td>555</td><td>39.64</td></tr><tr><td>
6</td><td>Jos Buttler </td><td>548</td><td>54.8</td></tr><tr><td>
7</td><td>Virat Kohli </td><td>530</td><td>48.18</td></tr><tr><td>
8</td><td>Suryakumar Yadav </td><td>512</td><td>36.57</td></tr><tr><td>
9</td><td>Dinesh Karthik </td><td>498</td><td>49.8</td></tr><tr><td>
10</td><td>Shikhar Dhawan </td><td>497</td><td>38.23</td></tr></tbody></table>






In [13]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import numpy as np

1. Get Data

In [14]:
data = array([[735,52.5],[684,52.61],[659,54.91],[602,43],[555,39.64],[548,54.8],[530,48.18],[512,36.57],[498,49.8],[497,38.23]])
data

array([[735.  ,  52.5 ],
       [684.  ,  52.61],
       [659.  ,  54.91],
       [602.  ,  43.  ],
       [555.  ,  39.64],
       [548.  ,  54.8 ],
       [530.  ,  48.18],
       [512.  ,  36.57],
       [498.  ,  49.8 ],
       [497.  ,  38.23]])

2. Normalize data

In [15]:
def scale_linear_bycolumn(rawpoints, high=100.0, low=0.0):
    mins = np.min(rawpoints, axis=0)
    maxs = np.max(rawpoints, axis=0)
    rng = maxs - mins
    return high - (((high - low) * (maxs - rawpoints)) / rng)
scaled_data=scale_linear_bycolumn(data)
scaled_data

array([[100.        ,  86.85932388],
       [ 78.57142857,  87.45910578],
       [ 68.06722689, 100.        ],
       [ 44.11764706,  35.05997819],
       [ 24.3697479 ,  16.7393675 ],
       [ 21.42857143,  99.4002181 ],
       [ 13.86554622,  63.304253  ],
       [  6.30252101,   0.        ],
       [  0.42016807,  72.13740458],
       [  0.        ,   9.05125409]])

3. Subtract the mean

In [16]:
m = mean(scaled_data.T, axis=1)
m
mean_data= scaled_data - m
scaled_data

array([[100.        ,  86.85932388],
       [ 78.57142857,  87.45910578],
       [ 68.06722689, 100.        ],
       [ 44.11764706,  35.05997819],
       [ 24.3697479 ,  16.7393675 ],
       [ 21.42857143,  99.4002181 ],
       [ 13.86554622,  63.304253  ],
       [  6.30252101,   0.        ],
       [  0.42016807,  72.13740458],
       [  0.        ,   9.05125409]])

4. compute covaraince matrix

In [17]:
covariance=cov(mean_data.T)
covariance

array([[1253.67794176,  777.74112189],
       [ 777.74112189, 1487.26275274]])

5. Compute eigen  values and vectors

In [18]:
values, vectors = eig(covariance)
print("vectors")
print(vectors)
print("eigen values")
print(values)

vectors
[[-0.75779405 -0.65249381]
 [ 0.65249381 -0.75779405]]
eigen values
[ 584.00882965 2156.93186485]


9. Choose components and form feature vectors

In [19]:
P = vectors.T.dot(mean_data.T)
P.T

array([[-29.23301937, -64.57242244],
       [-12.60322143, -51.04492333],
       [  3.53965601, -53.69441177],
       [-20.68445727,  11.14370312],
       [-17.67370187,  37.91233494],
       [ 38.49079772, -22.8084665 ],
       [ 20.66961935,   9.47966829],
       [-14.90479852,  62.38608181],
       [ 36.62202368,  11.55898462],
       [ -4.2228983 ,  59.63945126]])